CREATE DATABASE DOMFACONE;

USE DOMFACONE;

CREATE TABLE PRODUTOS(
	PRODUTOID INT NOT NULL AUTO_INCREMENT,
    NOMEPRODUTO VARCHAR(500) NOT NULL,
    IMAGEM VARCHAR(5000) NOT NULL,
    QUANTIDADE INT NOT NULL,
    PRECO DECIMAL(15, 2) NOT NULL,
    DESCRICAO VARCHAR(5000) NOT NULL,
	PRIMARY KEY(PRODUTOID)
);

-- INSERT INTO PRODUTOS (NOMEPRODUTO, IMAGEM, QUANTIDADE, PRECO, DESCRICAO)
-- VALUES ('NOME', 'imagem', 10, 5.20, 'descricao do produto'); 

-- INSERT INTO PRODUTOS (NOMEPRODUTO, IMAGEM, QUANTIDADE, PRECO, DESCRICAO)
-- VALUES ('NOME2', 'imagem2', 20, 15.20, 'descricao do produto 2'); 


SELECT * FROM PRODUTOS